In [5]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_csv("../data/cleaned_data/DataCoSupplyChain_Cleaned.csv", parse_dates = ["order_date_dateorders","shipping_date_dateorders"])

In [9]:
df.head()

,type,days_for_shipping_real,days_for_shipment_scheduled,benefit_per_order,sales_per_customer,delivery_status,late_delivery_risk,category_name,customer_city,customer_country,...,order_profit_per_order,order_region,order_state,order_status,product_image,product_name,product_price,shipping_date_dateorders,shipping_mode,Customer_name
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,Sporting Goods,Caguas,Puerto Rico,...,91.250000,Southeast Asia,Java Occidental,COMPLETE,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,2018-02-03 22:56:00,Standard Class,Cally Holloway
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,Sporting Goods,Caguas,Puerto Rico,...,-249.089996,South Asia,Rajastán,PENDING,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,2018-01-18 12:27:00,Standard Class,Irene Luna
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,Sporting Goods,San Jose,EE. UU.,...,-247.779999,South Asia,Rajastán,CLOSED,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,2018-01-17 12:06:00,Standard Class,Gillian Maldonado
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,Sporting Goods,Los Angeles,EE. UU.,...,22.860001,Oceania,Queensland,COMPLETE,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,2018-01-16 11:45:00,Standard Class,Tana Tate
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,Sporting Goods,Caguas,Puerto Rico,...,134.210007,Oceania,Queensland,PENDING_PAYMENT,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,2018-01-15 11:24:00,Standard Class,Orli Hendricks

In [10]:
df.dtypes

type                                      str
days_for_shipping_real                  int64
days_for_shipment_scheduled             int64
benefit_per_order                     float64
sales_per_customer                    float64
delivery_status                           str
late_delivery_risk                      int64
category_name                             str
customer_city                             str
customer_country                          str
customer_id                             int64
customer_segment                          str
customer_street                           str
latitude                              float64
longitude                             float64
market                                    str
order_city                                str
order_country                             str
order_customer_id                       int64
order_date_dateorders          datetime64[us]
order_id                                int64
order_item_cardprod_id                  int64
order_item_discount                   float64
order_item_discount_rate              float64
order_item_id                           int64
order_item_product_price              float64
order_item_profit_ratio               float64
order_item_quantity                     int64
sales                                 float64
order_item_total                      float64
order_profit_per_order                float64
order_region                              str
order_state                               str
order_status                              str
product_image                             str
product_name                              str
product_price                         float64
shipping_date_dateorders       datetime64[us]
shipping_mode                             str
Customer_name                             str
dtype: object

In [17]:
df["order_year"] = df["order_date_dateorders"].dt.year
df[["order_date_dateorders","order_year"]].head()

  order_date_dateorders  order_year
0   2018-01-31 22:56:00        2018
1   2018-01-13 12:27:00        2018
2   2018-01-13 12:06:00        2018
3   2018-01-13 11:45:00        2018
4   2018-01-13 11:24:00        2018

In [22]:
df["order_month_name"] = df["order_date_dateorders"].dt.month_name()
df[["order_date_dateorders","order_month_name"]].head()

  order_date_dateorders order_month_name
0   2018-01-31 22:56:00          January
1   2018-01-13 12:27:00          January
2   2018-01-13 12:06:00          January
3   2018-01-13 11:45:00          January
4   2018-01-13 11:24:00          January

In [24]:
df["order_quarter"] = df["order_date_dateorders"].dt.quarter
df[["order_date_dateorders","order_quarter"]].head()

  order_date_dateorders  order_quarter
0   2018-01-31 22:56:00              1
1   2018-01-13 12:27:00              1
2   2018-01-13 12:06:00              1
3   2018-01-13 11:45:00              1
4   2018-01-13 11:24:00              1

In [26]:
df["order_day_name"] = df["order_date_dateorders"].dt.day_name()
df[["order_date_dateorders","order_day_name"]].head()

  order_date_dateorders order_day_name
0   2018-01-31 22:56:00      Wednesday
1   2018-01-13 12:27:00       Saturday
2   2018-01-13 12:06:00       Saturday
3   2018-01-13 11:45:00       Saturday
4   2018-01-13 11:24:00       Saturday

In [37]:
df["shipping_duration_days"] = (df["shipping_date_dateorders"]-df["order_date_dateorders"]).dt.days
df["shipping_duration_days"].head()

0    3
1    5
2    4
3    3
4    2
Name: shipping_duration_days, dtype: int64

In [39]:
df["is_weekend_order"] = df["order_day_name"].isin(["Saturday", "Sunday"])
df["is_weekend_order"].head()

0    False
1     True
2     True
3     True
4     True
Name: is_weekend_order, dtype: bool

In [69]:
df["profit_margin_percentage"] = ((df["benefit_per_order"]/df["sales_per_customer"])*100).round(2)
df["profit_margin_percentage"].head()

0    29.0
1   -80.0
2   -80.0
3     7.5
4    45.0
Name: profit_margin_percentage, dtype: float64

In [76]:
df["discount_amount"] = (df["order_item_quantity"] * df["order_item_discount"]).round(2)
df["discount_amount"].head()

0   -12.11
1   -15.39
2   -17.03
3   -21.94
4   -28.50
Name: discount_amount, dtype: float64

In [81]:
df["delivery_delay_days"] = df["days_for_shipping_real"] - df["days_for_shipment_scheduled"]
df["delivery_delay_days"].head()

0   -1
1    1
2    0
3   -1
4   -2
Name: delivery_delay_days, dtype: int64

In [87]:
df["is_late_delivery"] = df["late_delivery_risk"] > 0
df["is_late_delivery"].head()

0    False
1     True
2    False
3    False
4    False
Name: is_late_delivery, dtype: bool

In [89]:
df.to_csv(
    "../data/feature_engineered_data/dataco_feature_engineered.csv",
    index=False
)